### PR TITLE
Added Leetcode problem in c++

### PR DESCRIPTION
**Pull request by Joseph2001-braganza**

### CODE REVIEW

**Comment by MaheshDoiphode** [comment]
Provide LeetCode question number and problem name to the file and then recommit.
Eg - "1.Two_Sum.py"

**Comment by Joseph2001-braganza** [comment]
done

**Comment by MaheshDoiphode** [comment]
Thanks for the contribution dude. Accepted the pull request. You can send multiple pull requests if you are not done with your 4 requests.
Thanks Again.

**Comment by Joseph2001-braganza** [comment]
sure,
thanks

**Pull request merged**
