### PR TITLE
Minimum Window Substring Problem

### PR DESCRIPTION
**Pull request by Srishti2128**
Easy to understand solution with comments for Minimum Window Substring Problem

### CODE REVIEW

**Comment by MaheshDoiphode** [comment]
Provide LeetCode question number and problem name to the file and then recommit.
Eg - "1.Two_Sum.java"

**Comment by Srishti2128** [comment]
> Provide LeetCode question number and problem name to the file and then recommit. Eg - "1.Two_Sum.java"

I have made the changes and recommitted. Kindly have a look.

**Comment by MaheshDoiphode** [comment]
Thanks for the contribution dude. Accepted the pull request. You can send multiple pull requests if you are not done with your 4 requests.
Thanks Again.

**Comment by Srishti2128** [comment]
> Thanks for the contribution dude. Accepted the pull request. You can send multiple pull requests if you are not done with your 4 requests. Thanks Again.

Sure. I have made one more PR and more are on the way. Thank you so much for the quick review.

**Pull request merged**
